### ISSUE TITLE
For members, how do i see their roles - observer, voting member, etc? 

### ISSUE THREAD

**Issue by OASIS-OP-Admin** [oasis-dev/it-transformation#49]
And where do i manage those roles? I see the roster on the workspace page but don't see how to modify anyone's role.

**Comment by OASIS-OP-Admin** [comment]
I found it - I didn't see the difference between the Members link and the Roster link. This should be documented

**Comment by OASIS-OP-Admin** [comment]
Changed the tag to documentation

**Comment by scottmcgrath** [comment]
Roles are shown in workspace rosters.    We can hide the link to the  Member is we want.

**Comment by OASIS-OP-Admin** [comment]
Will the Member link be publicly visible? Do we need a public list of TC members? I thought we required that.

**Comment by KellyCul** [comment]
I think this issue is resolved.

Rosters are behind the 'workspace' tab. This does require a log in, but non-members can make a free account. Not an ideal situation, but it is a start.

We need to manage any changes via Salesforce with OASIS staff via this form or an emial to us: https://www.oasis-open.org/tc-member-join-request-and-role-change-request/


I amgoing to close this ticket.
